const Animals = [
  {
    title: "An orangutan eating hay in a zoo enclosure",
    tags: [
      "Wildlife",
      "Mammal",
      "Animals Images & Pictures",
      "Ape",
      "Orang Utan",
      "Nature Images",
      "Primate",
      "Hd Grey Wallpapers",
      " Monkey Images",
      "Orangutan",
      "Creative Commons Images",
    ],
    location: "London",
    likes: 12,
    category: "animals",
    imgUrl:
      "https://res.cloudinary.com/de3lslau1/image/upload/v1704720600/Animals/william-warby-ajSHjoiWGKY-unsplash_g9vpjy.jpg",
  },
  {
    title: "A Brown Lion  ",
    tags: [
      "Kgalagadi",
      "South Africa",
      "Lion Images",
      "Animals Images & Pictures",
      "Wildlife",
      "Mammal",
      "Free Images",
    ],
    location: "London",
    likes: 2,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1590668468552-d87c3a011afb?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "A Brown Horse  ",
    tags: [
      "New Forest National Park",
      "United Kingdom",
      "Horse Images",
      "Winter Morning",
      "Winter Images & Pictures",
      "Countryside",
      "Wild Horse",
      "Pony",
      "Cold",
      "New Forest",
      "Ground",
      "Mammal",
      "Animals Images & Pictures",
      "Cow Images & Pictures",
      "Cattle",
      "Colt Horse",
      "Hd Grey Wallpapers",
      "Foal",
      "Outdoors",
      "Road",
      "HD Wallpapers",
    ],
    location: "London",
    likes: 192,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1613043437820-31039f9d9517?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Female Lion ",
    tags: [
      "Animals Images & Pictures",
      "Ngorongoro Crater",
      "Tanzania",
      "Mammal",
      "Lion Images",
      "Wildlife",
      "Predator",
      "Feline",
      "Carnivore",
      "Cat Images & Pictures",
      "Big Cat",
      "Brown Backgrounds",
      "Bokeh",
      "Safari",
    ],
    location: "London",
    likes: 92,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1496707679973-93555d880ac0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "A Giraffe Picture",
    tags: [
      "nimals Images & Pictures",
      "Giraffe Images & Pictures",
      "Serengueti",
      "Wildlife",
      "Aninal",
      "Wild",
      "Giraffe ",
      "Tanzania",
      "Africa",
      "Nature Images",
      "Mammal",
      "HD Wallpapers",
    ],
    location: "London",
    likes: 17,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1549854233-ca0baec6fa74?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Penguins captured at Berthas Beach, Falkland Islands",
    tags: [
      "Falkland Islands (Islas Malvinas)",
      "Penguin Pictures & Images",
      "Nature Images",
      "Sea",
      "Coast",
      "Beach Images & Pictures",
      "Hd Grey Wallpapers",
      "Island",
      "Nationalgeographic",
      "Beak",
      "Birds Images",
      "Animals Images & Pictures",
      "Shoreline",
      "Hd Ocean Wallpapers",
      "Outdoors",
      "Hd Water Wallpapers",
      "King Penguin",
      "Free Stock Photos",
    ],
    location: "London",
    likes: 92,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1704319180538-f57994377412?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Poison Dart Frog",
    tags: [
      "Frog Images",
      "Wildlife",
      "Animals Images & Pictures",
      "Amphibian",
      "Close Up",
      "Asia",
      "Poison-Arrow Frog",
      "Poison Dart Frog",
      "Nature Images",
      "Far East",
      "Hd Blue Wallpapers",
      "Singapore Zoo",
      "Singapore",
      "Keywords: Asia",
      "Lizard",
      "Reptile",
      "Tree Frog",
      "Free Pictures",
    ],
    location: "London",
    likes: 82,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1704112745943-2e66b8aece02?q=80&w=1975&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Arni the french Bulldog on field",
    tags: [
      "Dog Images & Pictures",
      "Pet",
      "Animals Images & Pictures",
      "French Bulldog",
      "Frenchie Dog",
      "Frenchie",
      "Doglove",
      "Portrait",
      "Beige",
      "Hd Autumn Wallpapers",
      "Field",
      "Dog Images & Pictures",
      "Bully",
    ],
    location: "London",
    likes: 42,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1665571299275-c356882f80df?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Cheetah",
    tags: [
      "Hd Grey Wallpapers",
      "Animals Images & Pictures",
      "Wildlife",
      "Mammal",
      "Cheetah Pictures & Images",
      "Cat Images & Pictures",
      "Nature Images",
      "Jaguar",
      "Panther",
      "Leopard",
      "Backgrounds",
    ],
    location: "London",
    likes: 22,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1703868673817-1cd9ec232d0f?q=80&w=1973&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title:
      "A morning drive through the Masari Mara included a visit with some zebra.",
    tags: [
      "Animals Images & Pictures",
      "Africa",
      "Wildlife",
      "Safari",
      "Kenya",
      "Masai Mara National Reserve",
      "Zebra",
      "Brown Backgrounds",
      "Masai Mara",
      "Tree Images & Pictures",
      "Zebras",
      "Grass Backgrounds",
      "Mammal",
      "Grassland",
      "Savanna",
      "Nature Images",
      "Field",
      "Outdoors",
      "Public Domain Images",
    ],
    location: "London",
    likes: 55,
    category: "animals",
    imgUrl:
      "https://images.unsplash.com/photo-1515205244153-fce4e5d8bc49?q=80&w=1904&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

const Wallpapers = [
  {
    title: "London Bridge Wallpaper",
    tags: [
      "London",
      "Uk",
      "Hd Wallpapers",
      "Hq Background Images",
      "Bridge",
      "Tower Bridge",
      "Landmark",
      "England",
      "Long Exposure Water",
      "Thames",
      "River",
      "River Thames",
      "Archicture",
      "Landmark Building",
      "Landmark Bridge",
      "Hd Wallpapers",
      "Hd Grey Wallpapers",
      "Creative Commons Images",
    ],
    location: "London",
    likes: 56,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1704234257809-9cbc16c6a7c7?q=80&w=1787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title:
      "A crisp half-moon against the serene blue twilight sky, showcasing the beauty of the celestial in stark contrast to the darkening heavens.",
    tags: [
      "Astronomy",
      "Night",
      "Space Images & Pictures",
      "Twilight",
      "Celestial",
      "Lunar",
      "Lunar Phase",
      "Moonlight",
      "High Resolution Images",
      "Mobile Wallpaper",
      "Hd Wallpapers",
      "Calm",
      "Serene",
      "Hd Dark Wallpapers",
      "Night Glow",
      "Celestial Photography",
      "Moon Surface",
      "Night Photography",
      "Quiet",
      "Peaceful Pictures",
      "Free Images",
    ],
    location: "London",
    likes: 2,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1704534268274-6d2f1e380ee2?q=80&w=2073&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Crashing waves by a red bridge",
    tags: [
      "Iphone Backgrounds",
      "Hd Iphone Wallpapers",
      "San Francisco",
      "Baker Beach",
      "Hq Background Images",
      "Hd Wallpapers",
      "Hd Android Wallpapers",
      "United States",
      "Hd Ocean Wallpapers",
      "Golden Gate",
      "Suspension Bridge",
      "Golden Gate Bridge",
      "Hd Lock Screen Wallpapers",
      "Bridge",
      "Crash",
      "Dusk",
      "Hd Wave Wallpapers",
      "Splash",
      "Red Bridge",
      "Outdoors",
      "Creative Commons Images",
    ],
    location: "London",
    likes: 10,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1478583888903-ed8b1b964b1d?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Wallpaper",
    tags: [
      "Lago Di Nambino",
      "Pinzolo",
      "Autonomous Province Of Trento",
      "Italy Pictures & Images",
      "Hq Background Images",
      "Hd Wallpapers",
      "Tree Images & Pictures",
      "Plant",
      "Nature Images",
      "Outdoors",
      "Fir",
      "Abies",
      "Housing",
      "Hd Water Wallpapers",
      "Lake",
      "House Images",
      "Hd Scenery Wallpapers",
      "Pine",
      "Landscape Images & Pictures",
      "Mountain Images & Pictures",
      "Backgrounds",
    ],
    location: "London",
    likes: 22,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1667206742636-2f7ae349a3f4?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Finnland, Salla -30 degrees winter wonderland 🥶",
    tags: [
      "Nature Images",
      "Hq Background Images",
      "Hd Wallpapers",
      "Tree Images & Pictures",
      "Hd Forest Wallpapers",
      "Hd Snow Wallpapers",
      "Winter Images & Pictures",
      "Snowcovered",
      "Freezing",
      "Cold",
      "Frozen",
      "Lake",
      "Natur",
      "Hd Wallpapers",
      "Fir",
      "Abies",
      "Outdoors",
      "Hd Scenery Wallpapers",
      "Land",
      "Landscape Images & Pictures",
      "Free Pictures",
    ],
    location: "London",
    likes: 78,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1704369671954-88ffd3b8bfa9?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "A lone fever tree on the edge of the Etosha salt pan in Namibia.",
    tags: [
      "Namibia",
      "Hd Wallpapers",
      "Etosha Pan",
      "Hq Background Images",
      "Etosha",
      "Lone Tree",
      "Ground",
      "Free Pictures",
    ],
    location: "London",
    likes: 67,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1668595472880-56b04e416b2f?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: " Anime Backgrounds",
    tags: [
      "Hd City Wallpapers",
      "Seoul",
      "Korea",
      "South Korea",
      "Hq Background Images",
      "Urban",
      "Hd Blue Wallpapers",
      "Hd Art Wallpapers",
      "Hd Anime Wallpapers",
      "Cityscape",
      "Landscape Images & Pictures",
      "Hd Wallpapers",
      "Building",
      "Town",
      "High Rise",
      "Metropolis",
      "Downtown",
      "Architecture",
      "Nature Images",
      "Apartment Building",
      "HD Wallpapers",
    ],
    location: "London",
    likes: 34,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1554310603-d39d43033735?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Wallpapers, Health & Wellness",
    tags: [
      "Sports Images",
      "Surf",
      "Bali",
      "Indonesia",
      "Wellness",
      "Hd Grey Wallpapers",
      "Hd Ocean Wallpapers",
      "Outdoors",
      "Human",
      "People Images & Pictures",
      "Sports Images",
      "Surfing",
      "Surf Spot",
      "Atlantic Ocean",
      "Hd Blue Wallpapers",
      "Freedom",
      "Hd Water Wallpapers",
      "Sea",
      "Nature Images",
      "Sea Waves",
    ],
    location: "London",
    likes: 32,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1563575044224-569da2f35b01?q=80&w=1885&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "SpaceX Falcon Heavy Launch",
    tags: [
      "Space Images & Pictures",
      "Science",
      "Rocket",
      "Kennedy Space Center",
      "Merritt Island",
      "United States",
      "Aerospace",
      "History",
      "Hq Background Images",
      "Hd Wallpapers",
      "Explosion",
      "Expedition",
      "Project",
      "Brave",
      "Skyline",
      "Cloudscape",
      "Smoke Backgrounds",
      "Spacex",
      "Falcon Heavy",
      "Tech",
      "HD Wallpapers",
    ],
    location: "London",
    likes: 22,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Nature Wallpapers",
    tags: [
      "Nature Images",
      "Hq Background Images",
      "Hd Wallpapers",
      "Hd Grey Wallpapers",
      "Outdoors",
      "Mountain Images & Pictures",
      "Mountain Range",
      "Peak",
      "Hd Scenery Wallpapers",
      "Hd Sky Wallpapers",
      "Ice",
      "Night",
      "Urban",
      "Cityscape",
      "Landscape Images & Pictures",
      "Glacier",
      "Public Domain Images",
    ],
    location: "London",
    likes: 22,
    category: "wallpapers",
    imgUrl:
      "https://images.unsplash.com/photo-1704206006658-4db30414c3f4?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

const Nature = [
  {
    title: "Purple Forest",
    tags: [
      "Nature Images",
      "Spain",
      "Hoz De Jaca",
      "Woodland",
      "Hd Forest Wallpapers",
      "Land",
      "Outdoors",
      "Plant",
      "Tree Images & Pictures",
      "Vegetation",
      "Hd Scenery Wallpapers",
      "Wilderness",
      "Grove",
      "Landscape Images & Pictures",
      "Weather",
      "Aerial View",
      "Hd Snow Wallpapers",
      "Abies",
      "Fir",
      "Ice",
      "Free Pictures",
    ],
    location: "London",
    likes: 78,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1704827260733-5569f0432250?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Nature",
    tags: [
      "Nature Images",
      "Flower Images",
      "Macro Flower",
      "Bohemian Pictures",
      "Hd White Wallpapers",
      "Plant",
      "Daisy",
      "Petal",
      "Outdoors",
      "Free Pictures",
    ],
    location: "London",
    likes: 87,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1687443543514-1038d371e895?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Nature Animal",
    tags: [
      "Nature Images",
      "On",
      "Evergreen Brick Works",
      "Bayview Avenue",
      "Toronto",
      "Canada",
      "Finch",
      "Birds Images",
      "Canary",
      "Park",
      "Summer Images & Pictures",
      "Flower Images",
      "Grass Backgrounds",
      "Animals Images & Pictures",
      "Free Stock Photos",
    ],
    location: "London",
    likes: 67,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1696253030104-cc8eae1e8f8e?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Dead trees at Sossusvlei taken just after dawn.",
    tags: [
      "Sossusvlei",
      "Namibia",
      "Nature Images",
      "Desert Images",
      "Dawn",
      "Tree Images & Pictures",
      "Ground",
      "Outdoors",
      "Brown Backgrounds",
      "Plant",
      "Tree Images & Pictures",
      "Public Domain Images",
    ],
    location: "London",
    likes: 87,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1704137480286-f41885d59214?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Peyto Lake rarely disappoints. This evening was no different",
    tags: [
      "Nature Images",
      "Mountain Images & Pictures",
      "Canada",
      "Peyto Lake",
      "Landscape Images & Pictures",
      "Sunset Images & Pictures",
      "Hd Snow Wallpapers",
      "Hd Sky Wallpapers",
      "Alberta",
      "Hd Wallpapers",
      "Peak",
      "Outdoors",
      "Mountain Range",
      "Dusk",
      "Sunrise",
      "Dawn",
      "Red Sky",
      "Glacier",
      "Ice",
      "Plateau",
      "Backgrounds",
    ],
    location: "London",
    likes: 76,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1507768738058-c38687b47c36?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Nature Image",
    tags: [
      "Nature Images",
      "Usa",
      "Ca",
      "Emerald Bay",
      "Hd Grey Wallpapers",
      "Outdoors",
      "Land",
      "Sea",
      "Hd Ocean Wallpapers",
      "Hd Water Wallpapers",
      "Hd Scenery Wallpapers",
      "Lake",
      "Vegetation",
      "Tree Images & Pictures",
      "Shoreline",
      "Woodland",
      "Hd Forest Wallpapers",
      "Landscape Images & Pictures",
      "Island",
      "Rainforest",
      "Free Images",
    ],
    location: "London",
    likes: 87,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1704132179311-1fea59acfef0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: " Wallpapers Nature",
    tags: [
      "Nature Images",
      "Indonesien",
      "Papua Barat",
      "Indonesia",
      "Misool",
      "Raja",
      "Papua",
      "Island",
      "Outdoors",
      "Jungle Backgrounds",
      "Land",
      "Rainforest",
      "Lake",
      "Hd Forest Wallpapers",
      "Lagoon",
      "Hd Green Wallpapers",
      "Hd Scenery Wallpapers",
      "Hd Ocean Wallpapers",
      "Aerial View",
      "Creative Commons Images",
    ],
    location: "London",
    likes: 67,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1703769605311-a8a837521cbb?q=80&w=1896&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: " Plant",
    tags: [
      "Nature Images",
      "Hd Forest Wallpapers",
      "Land",
      "Outdoors",
      "Plant",
      "Vegetation",
      "Woodland",
      "Tree Images & Pictures",
      "Aerial View",
      "Road",
      "Hd Green Wallpapers",
      "Brown Backgrounds",
      "Hd Water Wallpapers",
      "Creative Commons Images",
    ],
    location: "London",
    likes: 98,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1704138162406-bc43d5b9ff97?q=80&w=1936&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Palm Tree Pictures & Images",
    tags: [
      "Nature Images",
      "Tree Images & Pictures",
      "Hd Sky Wallpapers",
      "Sunset Images & Pictures",
      "Summer Images & Pictures",
      "Hq Background Images",
      "Landscape Images & Pictures",
      "Palm Tree Pictures & Images",
      "Plant",
      "Exotic",
      "Vibes",
      "Hd Blue Wallpapers",
      "Flora",
      "Arecaceae",
      "Silhouette",
      "Red Sky",
      "Outdoors",
      "Dawn",
      "Dusk",
      "Sunrise",
      "Backgrounds",
    ],
    location: "London",
    likes: 902,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1535392432937-a27c36ec07b5?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Sun Set",
    tags: [
      "Nature Images",
      "Sun Set",
      "Baltic Sea",
      "Cloud Sky",
      "Outdoors",
      "Dawn",
      "Red Sky",
      "Dusk",
      "Hd Scenery Wallpapers",
      "Sea",
      "Coast",
      "Beach Images & Pictures",
      "Hd Ocean Wallpapers",
      "Landscape Images & Pictures",
      "Flare",
      "Light Backgrounds",
      "Sea Waves",
      "Horizon",
      "Rock",
      "Promontory",
      "HD Wallpapers",
    ],
    location: "London",
    likes: 172,
    category: "Nature",
    imgUrl:
      "https://images.unsplash.com/photo-1704053339907-f2b3bfc2d349?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
const Travel = [
  {
    title: "White Island | Carriacou",
    tags: [
      "Nature Images",
      "Caribbean Beach",
      "Carriacou",
      "Travel Images",
      "Coral Reef",
      "Blue Ocean",
      "Blue Waters",
      "Sandbank",
      "Beach Images & Pictures",
      "White Island",
      "Hd Water Wallpapers",
      "Hd Ocean Wallpapers",
      "Outdoors",
      "Sea",
      "Shoreline",
      "Coast",
      "Aerial View",
      "Sea Life",
      "Animals Images & Pictures",
      "Shark Images & Pictures",
      "Free Pictures",
    ],
    location: "London",
    likes: 1982,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1704601312882-b294a46e0aca?q=80&w=1938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Mountain Images & Pictures",
    tags: [
      "Mountain Images & Pictures",
      "Triglav",
      "Fujifilm",
      "Park",
      "Slovenia",
      "Hut",
      "Outdoors",
      "Rural",
      "Building",
      "Countryside",
      "Nature Images",
      "Shelter",
      "Shack",
      "Housing",
      "Tree Images & Pictures",
      "Abies",
      "Fir",
      "House Images",
      "Cabin",
      "Cabin In The Woods",
      "Free Pictures",
    ],
    location: "London",
    likes: 102,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1704391943965-45b4cbc9a931?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Town Steeple",
    tags: [
      "Street Photography",
      "Dresden",
      "Germany",
      "Hd City Wallpapers",
      "Town",
      "Bell Tower",
      "Tower",
      "Building",
      "Urban",
      "Clock Tower",
      "Steeple",
      "Spire",
      "Gothic Arch",
      "Arch",
      "Arched",
      "Street",
      "Road",
      "Metropolis",
      "Alleyway",
      "Alley",
      "Public Domain Images",
    ],
    location: "London",
    likes: 1,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1704440541502-cbf2744ab740?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Boathouse on a mountain lake",
    tags: [
      "Nature Images",
      "Mountain Images & Pictures",
      "House Images",
      "Hd Grey Wallpapers",
      "Rural",
      "Outdoors",
      "Beautiful Pictures & Images",
      "Outdoor",
      "Shack",
      "Countryside",
      "Shelter",
      "Building",
      "Hut",
      "Glacier",
      "Hd Snow Wallpapers",
      "Ice",
      "Hotel",
      "Resort",
      "Cottage",
      "Housing",
      "Free Images",
    ],
    location: "London",
    likes: 82,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Tokyo Infinity For a full resolution photo, contact me directly.",
    tags: [
      "Hq Background Images",
      "Computer Backgrounds",
      "Tumblr Backgrounds",
      "Light Trail",
      "Illuminated",
      "Illumination",
      "City Street",
      "Street View",
      "Citylights",
      "Hd Modern Wallpapers",
      "Nighttime",
      "Sony",
      "Sonyalpha",
      "Longexposure",
      "Mobile",
      "Beautiful Pictures & Images",
      "Pic",
      "Birds Eye View",
      "Streets",
      "Populated",
      "Free Images",
    ],
    location: "London",
    likes: 22,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1498036882173-b41c28a8ba34?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Sunset Images & Pictures",
    tags: [
      "Hd City Wallpapers",
      "Hd Grey Wallpapers",
      "Archicture",
      "Sunset Images & Pictures",
      "Buildings",
      "Shanghai Skyline",
      "Shanghai",
      "Landscape Images & Pictures",
      "Cityscape",
      "Town",
      "Urban",
      "Building",
      "High Rise",
      "Architecture",
      "Metropolis",
      "Skyscraper",
      "Downtown",
      "Tower",
      "HD Wallpapers",
    ],
    location: "London",
    likes: 4,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1612756336279-b9eb5b6b71d9?q=80&w=2068&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Dji Spark",
    tags: [
      "Island Life",
      "Hd Tropical Wallpapers",
      "White Sand",
      "Island Hopping",
      "Palawan",
      "Dji Spark",
      "Paradise",
      "Beach Life",
      "Drone",
      "Sand",
      "Bar",
      "Sand Bar",
      "People Images & Pictures",
      "Cloudy",
      "Cloud Pictures & Images",
      "Hd Forest Wallpapers",
      "Hd Teal Wallpapers",
      "Yacht",
      "Coast",
      "Nature Images",
      "Public Domain Images",
    ],
    location: "London",
    likes: 92,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1521650559166-6b588715bc62?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Curvy road with car light trails at sunset.",
    tags: [
      "Hq Background Images",
      "California Pictures",
      "Usa",
      "Road",
      "Sunset Images & Pictures",
      "Hd Wallpapers",
      "Nature Images",
      "Outdoors",
      "Mountain Images & Pictures",
      "Flame",
      "Hd Scenery Wallpapers",
      "Dusk",
      "Dawn",
      "Red Sky",
      "Hd Sky Wallpapers",
      "Landscape Images & Pictures",
      "Freeway",
      "Sunrise",
      "Gravel",
      "Dirt Road",
      "Free Images",
    ],
    location: "London",
    likes: 120,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1622957830649-43ca384c6482?q=80&w=1933&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Natural rock bridge in the Hisma Desert – NEOM, Saudi Arabia",
    tags: [
      "Hd Scenery Wallpapers",
      "Scenic",
      "Vista",
      "Hd Wallpapers",
      "Hq Background Images",
      "Hd Wallpapers",
      "Hisma Desert – Neom",
      "Nature Images",
      "Landscape Images & Pictures",
      "Rock",
      "Outdoors",
      "Hd Cave Wallpapers",
      "Shoreline",
      "Coast",
      "Sea",
      "Cove",
      "Cliff",
      "People Images & Pictures",
      "Wilderness",
      "Arch",
      "Public Domain Images",
    ],
    location: "London",
    likes: 192,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1682685797857-97de838c192e?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "Building",
    tags: [
      "Building",
      "Animals Images & Pictures",
      "Antelope",
      "Mammal",
      "Wildlife",
      "Convention Center",
      "Office Building",
      "Women Images & Pictures",
      "Female",
      "People Images & Pictures",
      "Human",
      "Adult",
      "Terminal",
      "Arena",
      "Free Pictures",
    ],
    location: "London",
    likes: 1,
    category: "travel",
    imgUrl:
      "https://images.unsplash.com/photo-1703280030955-9acb01ea0338?q=80&w=2054&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
